BSIDM-352: So Cancel credit mngm
camptocamp/odoo-sale-addons pull request #8
Opened 2018-05-31 13:21 UTC by leemannd

[ADD]Give back credit to partner when the SO is canceled

2018-05-31 13:31 UTC, ghost reviewed
HISTORY?!

2018-05-31 13:42 UTC, leemannd commented
@oleksandrpaziuk There is no History in this repo

2018-05-31 13:46 UTC, ghost approved these changes
LGTM! :+1:

2018-05-31 13:52 UTC, guewen requested changes

2018-05-31 13:52 UTC, guewen commented on sale_credit_point/models/sale_order.py
> +                    sale.amount_total, "increase", "Sale Order canceled")
No translations?

2018-05-31 13:54 UTC, guewen commented on sale_credit_point/models/sale_order.py
> +                    sale.amount_total, "increase", "Sale Order canceled")
Is it normal that you have 2 calls which seems pretty similar (disclaimer: I didn't looked at the methods)

2018-05-31 14:10 UTC, leemannd commented
@guewen Yep, and tha't who it is used for instance into the wizard

2018-05-31 14:22 UTC, simahawk approved these changes
quick eyeball review: LG

2018-06-01 06:41 UTC, guewen approved these changes

2018-06-01 06:47 UTC, simahawk commented
@leemannd you'll have to rebase and raise version again after https://github.com/camptocamp/odoo-sale-addons/pull/7 is merged ;)

2018-06-01 08:00 UTC, leemannd commented
Version number raised

2018-06-01 08:00 UTC, leemannd commented
Fast tracking. Was green before rebase/squash

2018-06-01 08:00 UTC, merged