[FIX] check on website sale orders
camptocamp/odoo-sale-addons pull request #9
Opened 2018-06-08 16:56 UTC by mpanarin

When we come from the website, self.env.uid is 1, website orders are created by the admin user (sudo) because portal users don't have accesses on the models. So as soon as the user admin has 'sale_credit_point.group_manage_credit_point', all users will bypass the check.

2018-06-12 06:48 UTC, simahawk requested changes
can you update tests and a specific one?

2018-06-12 13:13 UTC, guewen requested changes
Great for the test, thanks :) An improvement for the creation of the test user:

2018-06-12 13:13 UTC, guewen commented on sale_credit_point/tests/test_sale_order.py
> +        self.portal_user = self.env["res.users"].create({
Set:

```
.with_context({
        'no_reset_password': True,
        'tracking_disable': True,
})
```
It will be faster :)

2018-06-13 07:26 UTC, simahawk requested changes
version upgrade missing too

2018-06-13 07:26 UTC, simahawk commented on sale_credit_point/tests/test_sale_order.py
> +        self.admin = self.env['res.users'].browse(1)
self.env.user is already admin here

2018-06-13 07:26 UTC, simahawk commented on sale_credit_point/tests/test_sale_order.py
> +        self.portal_user = self.env["res.users"].create({
+1, although, you don't need it since there's already a demo portal user https://github.com/odoo/odoo/blob/11.0/odoo/addons/base/base_demo.xml#L66

2018-06-13 12:43 UTC, yvaucher approved these changes

2018-06-13 12:44 UTC, yvaucher commented
bump @simahawk @guewen

2018-06-13 13:14 UTC, simahawk approved these changes

2018-06-13 13:15 UTC, merged